export default {
    overlay : document.getElementById("overlay"),
    loginBtn : document.getElementById("login_button"),
    errorModal : document.getElementById("error"),
    callback : document.getElementById("callbackBtn"),
    errorBlock : document.getElementById("errMsg"),
    modalWrap : document.getElementById("modal__wrap"),
    loginForm : document.getElementById("loginModal"),
    loginInput : document.getElementById("loginModal__login"),
    successMsg : document.getElementById("successMsg"),
    registerBtn : document.getElementById("register_button"),
    successForm : document.getElementById("successForm"),
    callbackForm : document.getElementById("callback"),
    passwordInput : document.getElementById("loginModal__password"),

    emptyError : "Field cannot be empty, please try again",
    existsError : "User with this login already exists",
    incorrectError : "Login or password does not match any account, please try again",
    successRegister : "Your account has been create successfully!",
    successLogin : "Welcome",
}